scoreboard objectives add db dummy db
scoreboard objectives add exp dummy exp
scoreboard objectives add level dummy level
scoreboard objectives add perkpoints dummy perkpoints
scoreboard objectives add strength dummy strength
scoreboard objectives add endurance dummy endurance
scoreboard objectives add alchemy dummy alchemy
scoreboard objectives add crafting dummy crafting
scoreboard objectives add charisma dummy charism
scoreboard objectives add player_deaths dummy Deaths
scoreboard players add @a level 0
scoreboard players add @a exp 0
scoreboard players add @a perkpoints 0
scoreboard players add @a strength 0
scoreboard players add @a endurance 0
scoreboard players add @a alchemy 0
scoreboard players add @a crafting 0
scoreboard players add @a charisma 0
scoreboard players add @a player_deaths 0